# Команды на linux
run-dist:
	./build/install/app/bin/app

build:
	./gradlew build || true

# Команды на windows
windows-run-dist:
	.\build\install\app\bin\app

windows-build:
	.\gradlew build || true