# Команды на linux
run-dist:
	./build/install/app/bin/app

# Команды на windows
windows-run-dist:
	.\build\install\app\bin\app

setup:
	chmod +x gradlew && ./gradlew clean install

hello:
	echo "hello"